### ISSUE TITLE
Trying to rotate "func_physbox" spams the server with errors

### ISSUE THREAD

**Issue by siobhan-saoirse** [BattlefieldDuck/TF2_PhysicsGun#2]
![image](https://user-images.githubusercontent.com/33694155/100916207-727c6280-34a3-11eb-845f-acd4270db200.png)

**Comment by main-thing** [comment]
The plugin can be fixed by changing code at line 341. Which is` float fSize = GetEntPropFloat(entity, Prop_Send, "m_flModelScale");` replace it with  
```
if (HasEntProp(entity, Prop_Send, "m_flModelScale")) {
float fSize = GetEntPropFloat(entity, Prop_Send, "m_flModelScale");
}
```
And the plugin should work fine now.
